# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-07-13 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='snippet',
            table='snippets',
        ),
    ]
